import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, CheckCircle2, FileText, Landmark, Network, ShieldCheck } from 'lucide-react';
import { contracts, services } from '@/lib/site-data';

export default function Home() {
  const featured = contracts.filter((item) => item.featured);
  return (
    <main>
      <section className="home-hero"><Image src="/thinh-vuong-legal-hero.png" alt="Minh họa pháp luật, ví điện tử và mạng thanh toán an toàn" fill priority sizes="100vw" /><div className="hero-overlay" /><div className="site-shell hero-content"><div className="hero-copy"><span className="eyebrow light">Pháp lý đi cùng kiến trúc sản phẩm</span><h1>Nền tảng pháp lý cho một ví điện tử <em>có thể mở rộng.</em></h1><p>Từ mô hình, doanh nghiệp và giấy phép đến hợp đồng API, dữ liệu và xử lý sự cố — một hệ thống thống nhất cho toàn bộ vòng đời dự án.</p><div className="hero-actions"><Link className="gold-button" href="/hop-dong">Tra cứu hợp đồng <ArrowRight /></Link><Link className="ghost-button" href="/dich-vu">Xem sáu nhóm dịch vụ</Link></div></div><div className="hero-proof"><div><strong>06</strong><span>nhóm dịch vụ xuyên suốt</span></div><div><strong>20</strong><span>hợp đồng và bộ hồ sơ</span></div><div><strong>01</strong><span>trọng tâm: ví điện tử</span></div></div></div></section>
      <section className="positioning-section"><div className="site-shell positioning-grid"><div className="positioning-title"><span className="eyebrow">Giá trị cho nhà đầu tư</span><h2>Không chỉ có đủ giấy tờ.<br />Phải vận hành được.</h2></div><div className="positioning-copy"><p>Ví điện tử là dịch vụ trung gian thanh toán có điều kiện. Giấy chứng nhận đăng ký doanh nghiệp không đồng thời tạo quyền cung ứng dịch vụ. Một dự án đáng tin cậy cần đồng bộ quản trị, cấp phép, hợp đồng, công nghệ và kiểm soát rủi ro.</p><Link href="/kien-thuc">Đọc cơ sở pháp lý <ArrowUpRight /></Link></div></div></section>
      <section className="services-section"><div className="site-shell"><div className="section-heading"><div><span className="eyebrow">Hành trình pháp lý</span><h2>Sáu lớp bảo vệ dự án</h2></div><p>Mỗi kết quả của giai đoạn trước trở thành đầu vào cho giai đoạn tiếp theo.</p></div><div className="service-grid">{services.map((service) => <article className="service-card" key={service.id}><div className="service-number">{service.number}</div><div className="service-card-head"><h3>{service.title}</h3>{service.minimum && <span className="tier minimum">Tối thiểu (*)</span>}{service.advanced && <span className="tier advanced">Nâng cao</span>}</div><p>{service.description}</p><div className="service-outcome"><CheckCircle2 /><span>{service.outcome}</span></div></article>)}</div><Link className="text-link" href="/dich-vu">Khám phá toàn bộ phạm vi dịch vụ <ArrowRight /></Link></div></section>
      <section className="featured-section"><div className="site-shell"><div className="section-heading inverse"><div><span className="eyebrow light">Hợp đồng tiêu biểu</span><h2>Điểm gặp giữa luật và vận hành</h2></div><p>Các mẫu giới thiệu nêu đúng đối tượng, phạm vi, điều khoản cốt lõi và giới hạn trách nhiệm.</p></div><div className="featured-contracts">{featured.map((item, index) => <Link href={`/hop-dong/${item.slug}`} key={item.slug} className="featured-card"><span>0{index + 1}</span><div><small>{item.minimum ? 'TỐI THIỂU (*)' : 'NÂNG CAO'}</small><h3>{item.shortTitle}</h3><p>{item.summary}</p></div><ArrowUpRight /></Link>)}</div><Link className="gold-button" href="/hop-dong">Mở thư viện 20 tài liệu <ArrowRight /></Link></div></section>
      <section className="principles-section"><div className="site-shell principles-grid"><div><span className="eyebrow">Nguyên tắc triển khai</span><h2>Bốn câu hỏi phải trả lời trước khi ký.</h2></div><div className="principle-list"><div><Landmark /><span><strong>Chủ thể nào có giấy phép?</strong> Tên gọi “nền tảng công nghệ” không đổi bản chất pháp lý.</span></div><div><Network /><span><strong>Tiền và dữ liệu đi đâu?</strong> Phạm vi pháp lý phải khớp luồng kỹ thuật và quyền truy cập.</span></div><div><FileText /><span><strong>Hồ sơ nào chứng minh tuân thủ?</strong> Mỗi nghĩa vụ cần đầu mối, biểu mẫu và dấu vết kiểm tra.</span></div><div><ShieldCheck /><span><strong>Khi có sự cố, ai quyết định?</strong> Phải bảo toàn chứng cứ và tuân thủ thời hạn bắt buộc.</span></div></div></div></section>
      <section className="cta-section"><div className="site-shell cta-inner"><div><span className="eyebrow light">Bắt đầu từ mô hình</span><h2>Biến yêu cầu pháp luật thành lộ trình có thể thực hiện.</h2></div><div><a className="gold-button" href="https://zalo.me/0961621602" target="_blank" rel="noreferrer">Trao đổi qua Zalo <ArrowUpRight /></a><span>Phản hồi theo phạm vi dự án học tập</span></div></div></section>
    </main>
  );
}
